### ISSUE TITLE
unc doen't compile with go 1.5beta2 (on darwin)

### ISSUE THREAD

**Issue by agonzalezro** [LK4D4/unc#2]
Hi @LK4D4,

I've tried to compile this on my machine and this is what I get:

```
$ go version
go version go1.5beta2 darwin/amd64

$ go build .
# github.com/LK4D4/unc
./container.go:22: unknown syscall.SysProcAttr field 'Cloneflags' in struct literal
./container.go:29: unknown syscall.SysProcAttr field 'UidMappings' in struct literal
./container.go:36: unknown syscall.SysProcAttr field 'GidMappings' in struct literal
```

**Comment by LK4D4** [comment]
@agonzalezro hmm, it's definitely works for me on. I think it's because you use Mac and I'm writing about Linux Containers. So those flags makes sense only for linux. You can write `_unsupported.go` version, but I think this program should be used on linux.

**Comment by agonzalezro** [comment]
Definitely, I didn't know that it was just for Linux but it completely makes sense. I will try in a container later :) Feel free to close this ticket.

**Comment by LK4D4** [comment]
@agonzalezro Thanks! Feel free to ask any questions!
