### ISSUE TITLE
 Container start failed: fork/exec operation not permitted on Centos7

### ISSUE THREAD

**Issue by woosley** [LK4D4/unc#5]
Hi, 
I was trying to run this project using a Non root account under Centos 7, but I got this error below 

```
[vagrant@localhost unc]$ go run main.go container.go
FATA[0000] Container start failed: fork/exec /tmp/go-build875495572/command-line-arguments/_obj/exe/main: operation not permitted
exit status 1
```
I think it might be related to the capability settings in the OS, but I have no idea what to look for,  I am wondering if you know anything about this?

**Comment by LK4D4** [comment]
@woosley you might want to check that your kernel supports user namespaces: there should be `/proc/self/ns/user` file.
Also, you need to check that there is `1` in `/proc/sys/kernel/unprivileged_userns_clone` and `Y` in `/sys/module/user_namespace/parameters/enabled`.
You can check that it works with `unshare -U` also.
Thanks!

**Comment by woosley** [comment]
the user namespace is enabled by this: 
```
grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
```
unshare -U works

```
[vagrant@localhost unc]$ unshare -U
[nfsnobody@localhost unc]$
```
but it might not related to user namespace. I commented CLONE_NEWUSER in the code, still got the same error

**Comment by LK4D4** [comment]
@woosley you can try to run with `strace -f` to see which syscall is problematic. Underlying of exec.Cmd is quite complicated and involve many moving parts and each of them might be broken :(

**Comment by woosley** [comment]
today I tried some other unshare options, it seems that on Centos 7, there are some permission setting blocking user to do namespace clone?

```
[vagrant@localhost unc]$ unshare -Um
unshare: unshare failed: Operation not permitted
[vagrant@localhost unc]$ unshare -Ui
[nfsnobody@localhost unc]$ logout
[vagrant@localhost unc]$ unshare -Uu
[nfsnobody@localhost unc]$ logout
[vagrant@localhost unc]$ unshare -Un
[nfsnobody@localhost unc]$ logout
[vagrant@localhost unc]$ unshare -p
unshare: unshare failed: Operation not permitted

```

**Comment by LK4D4** [comment]
@woosley yeap, looks like mount namespace is forbidden to do unprivileged. That might be related to fact that there was a pretty serious vulnerability with user and mount namespaces in certain kernel versions.
All namespace work for me in Ubuntu 16.04 with kernel 4.10 if that helps.
